{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "disentangle.serviceAccountName" . }}
  labels:
    {{- include "disentangle.labels" . | nindent 4 }}
{{- end }}
