apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: disentangle
  namespace: disentangle
spec:
  values:
    nodes:
      count: 5
    traffic:
      enabled: true
      interval: "*/5 * * * *"
      txCount: 10
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
