repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--allow-multiple-documents']
        exclude: 'helm/.*/templates/.*'
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['-d', 'relaxed']
        exclude: 'helm/.*/templates/.*'

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ['--severity=warning']

  - repo: local
    hooks:
      - id: helm-lint
        name: Helm Lint
        entry: helm lint helm/disentangle/
        language: system
        files: 'helm/.*\.(yaml|tpl)$'
        pass_filenames: false

      - id: helm-template
        name: Helm Template
        entry: bash -c 'helm template test helm/disentangle/ > /dev/null'
        language: system
        files: 'helm/.*\.(yaml|tpl)$'
        pass_filenames: false
