apiVersion: v2
name: disentangle
description: Helm chart for Disentangle Protocol network deployment
type: application
version: 0.2.0
appVersion: "v0.4.1"
license: Apache-2.0
keywords:
  - blockchain
  - post-quantum
  - dag
  - consensus
maintainers:
  - name: Disentangle Network
    url: https://github.com/disentangle-network
